Add repair_ro script and init.d service for root filesystem repair

diff --git a/.github/workflows/generate-openwrt.yml b/.github/workflows/generate-openwrt.yml
--- a/.github/workflows/generate-openwrt.yml
+++ b/.github/workflows/generate-openwrt.yml
@@ -39,6 +39,15 @@ on:
           - bcm2710-rpi-3b
           - bcm2711-rpi-4b
           - x86-64
+      fiturs:
+        description: "Select fitur"
+        required: true
+        default: "all"
+        type: choice
+        options:
+          - all
+          - full-fitur
+          - simpel
       notify:
         description: "Notify to Telegram"
         required: true
@@ -74,9 +83,8 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       devices: ${{ steps.matrix.outputs.devices }}
+      fiturs: ${{ steps.matrix.outputs.fiturs }}
       message_id: ${{ steps.telegram.outputs.message_id }}
-      release_name: ${{ steps.setup.outputs.release_name }}
-      release_tag: ${{ steps.setup.outputs.release_tag }}
       changelog: ${{ steps.changelog.outputs.changelog }}
       startbuildtime: ${{ steps.setup.outputs.startbuildtime }}
     steps:
@@ -94,51 +102,6 @@ jobs:
           r="${r//$'\n'/'%0A'}"
           r="${r//$'\r'/'%0D'}"  
           echo "changelog=$r" >> $GITHUB_OUTPUT 
-
-      - name: Setup Environment Variables
-        id: setup
-        run: |
-          sudo timedatectl set-timezone "$TZ"
-
-          STARTBUILDTIME=$(date +%s)
-          DATETIME=$(date +'%d%m%Y')
-
-          BRANCH_TAG=$(echo "${{ inputs.releases_branch }}" | tr ':' '_')
-
-          release_name() {
-              local source_name="${1%:*}"  # Ambil bagian sebelum ":"
-              local branch_version="${1#*:}"  # Ambil bagian setelah ":"
-              local release_for="$2"
-
-              case "$source_name" in
-                  openwrt) source_name="OpenWrt" ;;
-                  immortalwrt) source_name="ImmortalWrt" ;;
-                  *) echo "Error: Source tidak dikenali" >&2; return 1 ;;
-              esac
-
-              case "$release_for" in
-                  main) release_type="Stable" ;;
-                  dev) release_type="Development" ;;
-                  *) echo "Error: Jenis release tidak dikenali" >&2; return 1 ;;
-              esac
-
-              local tanggal=$(date +'%d-%m-%Y')
-
-              echo "RTA-WRT - $release_type | $source_name:$branch_version | $tanggal"
-          }
-
-          RELEASE_NAME=$(release_name "${{ inputs.releases_branch }}" "${{ github.ref_name }}")
-
-          case "${{ github.ref_name }}" in
-              main) RELEASE_TAG="${BRANCH_TAG}--main-${DATETIME}" ;;
-              dev) RELEASE_TAG="${BRANCH_TAG}--dev-${DATETIME}" ;;
-              *) echo "Error: Branch tidak dikenali" >&2; exit 1 ;;
-          esac
-
-          echo "startbuildtime=${STARTBUILDTIME}" >> $GITHUB_OUTPUT
-          echo "datetime=${DATETIME}" >> $GITHUB_ENV
-          echo "release_name=${RELEASE_NAME}" >> $GITHUB_OUTPUT
-          echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
 
       - name: Configure Build Matrix
         id: matrix
@@ -171,11 +134,27 @@ jobs:
           }
           EOJ
           )
+
+          FITUR_JSON=$(cat << 'EOJ'
+          {
+            "fiturs": [
+              "full-fitur",
+              "simpel"
+            ]
+          }
+          EOJ
+          )
           
           if [ "${{ inputs.devices }}" = "all" ]; then
             echo "devices=$(echo "$DEVICES_JSON" | jq -c '.devices')" >> $GITHUB_OUTPUT
           else
             echo "devices=$(jq -nc --arg d "${{ inputs.devices }}" '[$d]')" >> $GITHUB_OUTPUT
+          fi
+
+          if [ "${{ inputs.fiturs }}" = "all" ]; then
+             echo "fiturs=$(echo "$FITUR_JSON" | jq -c '.fiturs')" >> $GITHUB_OUTPUT
+          else
+             echo "fiturs=$(jq -nc --arg f "${{ inputs.fiturs }}" '[$f]'" >> $GITHUB_OUTPUT
           fi
 
       - name: Send Initial Telegram Message
@@ -184,9 +163,11 @@ jobs:
           BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
           CHAT_ID: ${{ secrets.CHAT_ID }}
         run: |
+          sudo timedatectl set-timezone "$TZ"
           THREAD_ID_BUILD=616
           
           devices='${{ steps.matrix.outputs.devices }}'
+          fiturs='${{ steps.matrix.outputs.fiturs }}'
 
           create_build_status_message() {
           cat << EOF
@@ -201,7 +182,9 @@ jobs:
           EOF
 
           while read -r device; do
-              echo "🔹 $device | ⏳ Building"
+              while read -r fitur; do
+                echo "🔹 $device $fitur | ⏳ Building"
+              done < <(echo "$fiturs" | jq -r '.[]')
           done < <(echo "$devices" | jq -r '.[]')
 
           echo "━━━━━━━━━━━━━━━━━━━━━━"
@@ -217,18 +200,77 @@ jobs:
           
           echo "message_id=$(echo $RESPONSE | jq -r '.result.message_id')" >> $GITHUB_OUTPUT
 
+      - name: Setup Environment Variables
+        id: setup
+        run: |
+          sudo timedatectl set-timezone "$TZ"
+
+          STARTBUILDTIME=$(date +%s)
+          echo "startbuildtime=${STARTBUILDTIME}" >> $GITHUB_OUTPUT
+
   build:
+    name: ${{ matrix.device }}-${{ matrix.fitur }} release
     needs: prepare
     runs-on: ubuntu-24.04
     strategy:
       fail-fast: false
       matrix:
         device: ${{ fromJSON(needs.prepare.outputs.devices) }}
+        fitur: ${{ fromJson(needs.prepare.outputs.fiturs) }}
+  
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref_name }}
+
+      - name: Create Releases Name
+        id: releases-name
+        run: |
+          sudo timedatectl set-timezone "$TZ"
+          release_name() {
+              local source_name="${1%:*}"  # Ambil bagian sebelum ":"
+              local branch_version="${1#*:}"  # Ambil bagian setelah ":"
+              local release_for="$2"
+              local fitur="$3"
+
+              case "$source_name" in
+                  openwrt) source_name="OpenWrt" ;;
+                  immortalwrt) source_name="ImmortalWrt" ;;
+                  *) echo "Error: Source tidak dikenali" >&2; return 1 ;;
+              esac
+
+              case "$release_for" in
+                  main) release_type="Stable" ;;
+                  dev) release_type="Development" ;;
+                  *) echo "Error: Jenis release tidak dikenali" >&2; return 1 ;;
+              esac
+
+              case "$fitur" in
+                  full-fitur) fitur_name="Full Fitur" ;;
+                  simpel) fitur_name="Simpel" ;;
+                  *) echo "Error: Fitur tidak dikenali" >&2; return 1 ;;
+              esac
+
+              local tanggal=$(date +'%d-%m-%Y')
+
+              echo "RTA-WRT - $release_type | $fitur_name | $source_name:$branch_version | $tanggal"
+          }
+          RELEASE_NAME=$(release_name "${{ inputs.releases_branch }}" "${{ github.ref_name }}" "${{ matrix.fitur }}")
+          echo "release_name=${RELEASE_NAME}" >> $GITHUB_OUTPUT
+
+          DATETIME=$(date +'%d%m%Y')
+
+          BRANCH_TAG=$(echo "${{ inputs.releases_branch }}" | tr ':' '_')
+
+          case "${{ github.ref_name }}" in
+              main) RELEASE_TAG="${BRANCH_TAG}-${{ matrix.fitur}}-main-${DATETIME}" ;;
+              dev) RELEASE_TAG="${BRANCH_TAG}-${{ matrix.fitur}}-dev-${DATETIME}" ;;
+              *) echo "Error: Branch tidak dikenali" >&2; exit 1 ;;
+          esac
+
+          echo "datetime=${DATETIME}" >> $GITHUB_ENV
+          echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
 
       - name: Install Dependencies
         run: |
@@ -250,13 +292,13 @@ jobs:
           OP_SOURCE="${OPEWRT%:*}"
           sed -i -E "s|baseOpenwrt: 'null'|baseOpenwrt: '${OP_SOURCE}'|g" files/usr/share/ucode/luci/template/header.ut
           sed -i -E "s|currentBranch: 'null'|currentBranch: '${{ github.ref_name }}'|g" files/usr/share/ucode/luci/template/header.ut
-          sed -i -E "s|currentVersion: 'null'|currentVersion: '${{ needs.prepare.outputs.release_tag }}'|g" files/usr/share/ucode/luci/template/header.ut
+          sed -i -E "s|currentVersion: 'null'|currentVersion: '${{ steps.releases-name.outputs.release_tag }}'|g" files/usr/share/ucode/luci/template/header.ut
 
       - name: Build Image
         id: build
         run: |
           chmod +x ${{ env.IMAGEBUILDER_SH }}
-          if sudo ./${{ env.IMAGEBUILDER_SH }} ${{ inputs.releases_branch }} "${{ matrix.device }}"; then
+          if sudo ./${{ env.IMAGEBUILDER_SH }} ${{ inputs.releases_branch }} "${{ matrix.device }}" "${{ matrix.fitur }}"; then
             echo "status=✅ Success" >> $GITHUB_OUTPUT
             echo "✅ Success" > status.txt
           else
@@ -269,7 +311,7 @@ jobs:
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: build-status-${{ matrix.device }}
+          name: build-status-${{ matrix.device }}-${{ matrix.fitur }}
           path: status.txt
           retention-days: 5
 
@@ -279,13 +321,13 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           files: imagebuilder/out_firmware/*
-          tag_name: ${{ needs.prepare.outputs.release_tag }}
-          name: ${{ needs.prepare.outputs.release_name }}
+          tag_name: ${{ steps.releases-name.outputs.release_tag }}
+          name: ${{ steps.releases-name.outputs.release_name }}
           body: |
             # 🚀 RTA-WRT - Release Information
             
             ## 📥 Download Statistics
-            ![GitHub Downloads](https://img.shields.io/github/downloads/${{ github.repository }}/${{ needs.prepare.outputs.release_tag }}/total?style=for-the-badge&logo=Openwrt)
+            ![GitHub Downloads](https://img.shields.io/github/downloads/${{ github.repository }}/${{ steps.releases-name.outputs.release_tag }}/total?style=for-the-badge&logo=Openwrt)
             
             ## 📢 Support Channels
             [![Channel](https://img.shields.io/badge/Telegram-Channel-%23059dfa?style=for-the-badge&logo=Telegram)](https://t.me/rtawrt) [![Group](https://img.shields.io/badge/Telegram-Group-%23059dfa?style=for-the-badge&logo=Telegram)](https://t.me/backup_rtawrt) [![Personal](https://img.shields.io/badge/Telegram-Personal-%23059dfa?style=for-the-badge&logo=Telegram)](https://t.me/RizkiKotet)
@@ -322,6 +364,7 @@ jobs:
           THREAD_ID_BUILD=616
 
           devices='${{ needs.prepare.outputs.devices }}'
+          fiturs='${{ needs.prepare.outputs.fiturs }}'
 
           format_time() {
             local total_seconds=$1
@@ -348,8 +391,10 @@ jobs:
           EOF
 
           while read -r device; do
-              status=$(cat "artifacts/build-status-$device/status.txt" 2>/dev/null || echo "❓ Unknown")
-              echo "🔹 $device | $status"
+            while read -r fitur; do
+              status=$(cat "artifacts/build-status-$device-$fitur/status.txt" 2>/dev/null || echo "❓ Unknown")
+              echo "🔹 $device $fitur | $status"
+            done < <(echo "$fiturs" | jq -r '.[]')
           done < <(echo "$devices" | jq -r '.[]')
 
           cat << EOF
@@ -428,11 +473,28 @@ jobs:
           }
 
           DEV_MESSAGE=$(create_dev_message)
+
+          DATETIME=$(date +'%d%m%Y')
+
+          BRANCH_TAG=$(echo "${{ inputs.releases_branch }}" | tr ':' '_')
+
+          case "${{ github.ref_name }}" in
+              main)
+                RELEASE_TAG_FULL="${BRANCH_TAG}-full-fitur-main-${DATETIME}"
+                RELEASE_TAG_SIMPEL="${BRANCH_TAG}-simpel-main-${DATETIME}"
+                ;;
+              dev)
+                RELEASE_TAG_FULL="${BRANCH_TAG}-full-fitur-dev-${DATETIME}"
+                RELEASE_TAG_SIMPEL="${BRANCH_TAG}-simpel-dev-${DATETIME}"
+                ;;
+              *) echo "Error: Branch tidak dikenali" >&2; exit 1 ;;
+          esac
         
           BUTTONS_STABLE='{
               "inline_keyboard": [
                   [
-                      {"text": "📥 Unduh Firmware", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${{ needs.prepare.outputs.release_tag }}"},
+                      {"text": "📥 Unduh Full Fiturs", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${RELEASE_TAG_FULL}"},
+                      {"text": "📥 Unduh Simpel", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${RELEASE_TAG_SIMPEL}"},
                       {"text": "📋 Status Build", "url": "https://t.me/backup_rtawrt/616/${{ needs.prepare.outputs.message_id }}"}
                   ]
               ]
@@ -441,7 +503,8 @@ jobs:
           BUTTONS_DEV='{
               "inline_keyboard": [
                   [
-                      {"text": "📥 Unduh Firmware", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${{ needs.prepare.outputs.release_tag }}"},
+                      {"text": "📥 Unduh Full Fiturs", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${RELEASE_TAG_FULL}"},
+                      {"text": "📥 Unduh Simpel", "url": "https://github.com/rizkikotet-dev/RTA-WRT/releases/tag/${RELEASE_TAG_SIMPEL}"},
                       {"text": "📋 Status Build", "url": "https://t.me/backup_rtawrt/616/${{ needs.prepare.outputs.message_id }}"}
                   ]
               ]
@@ -490,25 +553,30 @@ jobs:
           CURRENT_BRANCH: ${{ env.CURRENT_BRANCH }}
         run: |
           set -euo pipefail
-          OPEWRT="${{ inputs.releases_branch }}"
-          OP_SOURCE="${OPEWRT%:*}"
-          mkdir -p "${CURRENT_BRANCH}/${OP_SOURCE}"
-      
-          if [ -n "${{ needs.prepare.outputs.changelog }}" ]; then
-            changelog_content=$(echo "${{ needs.prepare.outputs.changelog }}" | \
-              sed -e 's/%0A/\n/g' \
-                  -e 's/%0D/\r/g' \
-                  -e 's/%25/%/g')
-            echo "${changelog_content}" > "${CURRENT_BRANCH}/${OP_SOURCE}/changelog.txt"
-            cat "${CURRENT_BRANCH}/${OP_SOURCE}/changelog.txt"
-          else
-            echo "No changelog content found"
-            exit 1
-          fi
-      
-          VERSION_TAG="${{ needs.prepare.outputs.release_tag }}"
-          echo "${VERSION_TAG}" > "${CURRENT_BRANCH}/${OP_SOURCE}/version.txt"
-      
+
+          fiturs='${{ needs.prepare.outputs.fiturs }}'
+          BRANCH_TAG=$(echo "${{ inputs.releases_branch }}" | tr ':' '_')
+          while read -r fitur; do
+            OPEWRT="${{ inputs.releases_branch }}"
+            OP_SOURCE="${OPEWRT%:*}"
+            mkdir -p "${CURRENT_BRANCH}/${OP_SOURCE}"
+        
+            if [ -n "${{ needs.prepare.outputs.changelog }}" ]; then
+              changelog_content=$(echo "${{ needs.prepare.outputs.changelog }}" | \
+                sed -e 's/%0A/\n/g' \
+                    -e 's/%0D/\r/g' \
+                    -e 's/%25/%/g')
+              echo "${changelog_content}" > "${CURRENT_BRANCH}/${OP_SOURCE}/${fitur}/changelog.txt"
+              cat "${CURRENT_BRANCH}/${OP_SOURCE}/${fitur}/changelog.txt"
+            else
+              echo "No changelog content found"
+              exit 1
+            fi
+        
+            VERSION_TAG="${BRANCH_TAG}-${fitur}-${CURRENT_BRANCH}-${DATETIME}"
+            echo "${VERSION_TAG}" > "${CURRENT_BRANCH}/${OP_SOURCE}/${fitur}/version.txt"
+          done < <(echo "$fiturs" | jq -r '.[]')
+          
           # Konfigurasi Git
           git config user.name 'github-actions[bot]'
           git config user.email 'github-actions[bot]@users.noreply.github.com'
